/**
 * Serialized strategy.
 */
export enum SerializedStrategy {
  PROFILE = 'profile',
  DB = 'db',
  SNAPSHOT = 'snapshot',
}

/**
 * Populate strategy.
 */
export enum PopulateStrategy {
  PROFILE = 'profile',
  DB = 'db',
}

/**
 * Sorting options.
 */
export enum CommunitySortOptions {
  NAME_ASC = 1,
  NAME_DESC = -1,
}

/**
 * Sorting options.
 */
export enum AchievemenentSortOptions {
  NAME_ASC = 1,
  NAME_DESC = -1,
}

/**
 * Sorting options.
 */
export enum CredentialSortOptions {
  ACHIEVEMENT_NAME_ASC = 1,
  ACHIEVEMENT_NAME_DESC = -1,
  STATE_ASC = 2,
  STATE_DESC = -2,
}

/**
 * Sorting options.
 */
export enum UserSortOptions {
  LAST_NAME_ASC = 1,
  LAST_NAME_DESC = -1,
}

/**
 * Webhook event kinds.
 */
export enum WebhookEventKind {
  ORDER_REQUEST_CHANGED = 0,
  ORDER_REQUEST_ERROR = 1,
  DEPLOY_REQUEST_CHANGED = 2,
  DEPLOY_REQUEST_ERROR = 3,
}

/**
 * Webhook interface definition.
 */
export interface Webhook {
  accountId: string;
  event: WebhookEventKind;
  requestRef: string;
}

/**
 * Default pagination values.
 */
export enum PaginationValues {
  PAGE_MAX_LIMIT = 100,
  PAGE_DEFAULT_LIMIT = 25,
}

/**
 * Wallet kinds.
 */
export enum WalletKinds {
  META_MASK = 1,
  BITSKI = 2,
}

/**
 * System Error codes.
 */
export enum SystemErrorCode {
  UNHANDLED_SYSTEM_ERROR = 500001,
  BLOCKCHAIN_CONNECTION_FAILED = 500002,
}

/**
 * Validator Error codes.
 */
export enum ValidatorErrorCode {
  PROFILE_EMAIL_NOT_PRESENT = 422001,
  PROFILE_EMAIL_NOT_VALID = 422002,
  PROFILE_EMAIL_ALREADY_TAKEN = 422003,
  PROFILE_PASSWORD_NOT_PRESENT = 422004,
  PROFILE_PASSWORD_NOT_VALID = 422005,
  PROFILE_ABILITIES_KIND_NOT_PRESENT = 422006,
  PROFILE_ABILITIES_KIND_NOT_VALID = 422007,
  PROFILE_FIRST_NAME_NOT_PRESENT = 422008,
  PROFILE_EMAIL_DOES_NOT_EXIST = 422009,
  PROFILE_LAST_NAME_NOT_PRESENT = 422010,
  PROFILE_PAYMENT_KIND_INVALID = 422011,
  PROFILE_PAYMENT_REFERENCE_NOT_PRESENT = 422012,
  PROFILE_PAYMENT_PROFILEID_NOT_PRESENT = 422013,
  COMMUNITY_NAME_NOT_PRESENT = 422014,
  COMMUNITY_DESCRIPTION_NOT_PRESENT = 422015,
  COMMUNITY_ABILITIES_KIND_NOT_PRESENT = 422016,
  COMMUNITY_ABILITIES_KIND_NOT_VALID = 422017,
  COMMUNITY_ABILITIES_COMMUNITY_NOT_PRESENT = 422019,
  COMMUNITY_COLLABORATORS_REQUEST_COMMUNITY_ID_NOT_PRESENT = 422020,
  COMMUNITY_ABILITIES_ID_NOT_PRESENT = 422021,
  KEY_ABILITIES_KIND_NOT_PRESENT = 422022,
  KEY_ABILITIES_KIND_NOT_VALID = 422023,
  ACHIEVEMENT_NAME_NOT_PRESENT = 422024,
  ACHIEVEMENT_TAG_NOT_PRESENT = 422025,
  ACHIEVEMENT_COURSE_ID_NOT_PRESENT = 422026,
  ACHIEVEMENT_DEPENDANTS_NOT_VALID = 422027,
  CREDENTIAL_ACHIEVEMENT_NOT_PRESENT = 422028,
  CREDENTIAL_PROFILE_ID_NOT_PRESENT = 422029,
  CREDENTIAL_STAGE_NOT_PRESENT = 422030,
  CREDENTIAL_CONDITIONS_NOT_MET = 422031,
  CREDENTIAL_STAGE_NOT_VALID = 422032,
  CREDENTIAL_COMMUNITY_NOT_PRESENT = 422033,
  CREDENTIAL_WALLET_NOT_PRESENT = 422034,
  LINK_WALLET_KIND_NOT_PRESENT = 422035,
  LINK_WALLET_KIND_NOT_VALID = 422036,
  LINK_WALLET_PARSED_WALLET_ADDRESS_NOT_VALID = 422037,
  WALLET_ADDRESS_NOT_PRESENT = 422038,
  WALLET_ADDRESS_NOT_VALID = 422039,
}

/**
 * Route Error codes.
 */
export enum RouteErrorCode {
  INVALID_PATH = 400000,
  PROFILE_NOT_IDENTIFIED = 400001,
  PROFILE_CREDENTIALS_INVALID = 400002,
  REQUEST_TOKEN_INVALID = 400003,
  NOT_AUTHORIZED_TO_UPDATE_PROFILE = 400004,
  NOT_AUTHORIZED_TO_DELETE_PROFILE = 400005,
  NOT_AUTHORIZED_TO_CHANGE_PASSWORD = 400006,
  NOT_AUTHORIZED_TO_AUTHENTICATE = 400007,
  PROFILE_DOES_NOT_EXIST = 400008,
  NOT_AUTHORIZED_TO_CHANGE_EMAIL = 400009,
  NOT_AUTHORIZED_TO_CREATE_COMMUNITY = 400010,
  NOT_AUTHORIZED_TO_DELETE_COMMUNITY = 400011,
  NOT_AUTHORIZED_TO_UPDATE_COMMUNITY = 400012,
  COMMUNITY_DOES_NOT_EXISTS = 400013,
  NOT_AUTHORIZED_TO_CREATE_KEY = 400014,
  NOT_AUTHORIZED_TO_DELETE_KEY = 400015,
  NOT_AUTHORIZED_TO_READ_KEY = 400016,
  NOT_AUTHORIZED_TO_CREATE_KEY_ABILITY= 400017,
  NOT_AUTHORIZED_TO_DELETE_KEY_ABILITY= 400018,
  KEY_DOES_NOT_EXISTS = 400019,
  PROFILE_NOT_COMMUNITY_COLLABORATOR = 400020,
  NOT_AUTHORIZED_TO_CREATE_COMMUNITY_ABILITY = 400021,
  NOT_AUTHORIZED_TO_DELETE_COMMUNITY_ABILITY = 400022,
  NOT_AUTHORIZED_TO_READ_COMMUNITY_ABILITY = 400023,
  NOT_AUTHORIZED_TO_CREATE_COMMUNITY_ACHIEVEMENT = 400024,
  NOT_AUTHORIZED_TO_UPDATE_COMMUNITY_ACHIEVEMENT = 400025,
  NOT_AUTHORIZED_TO_DELETE_COMMUNITY_ACHIEVEMENT = 400026,
  NOT_AUTHORIZED_TO_READ_COMMUNITY_ACHIEVEMENT = 400027,
  ACHIEVEMENT_DOES_NOT_EXIST = 400028,
  NOT_AUTHORIZED_TO_CREATE_CREDENTIAL = 400029,
  NOT_AUTHORIZED_TO_DELETE_CREDENTIAL = 400030,
  NOT_AUTHORIZED_TO_FINALISE_CREDENTIAL = 400031,
  NOT_AUTHORIZED_TO_READ_CREDENTIAL = 400032,
  CREDENTIAL_DOES_NOT_EXISTS = 400033,
  CREDENTIAL_IN_COMPLETE_STAGE_CANNOT_BE_DELETED = 400034,
  CREDENTIAL_IN_INVALID_STAGE = 400035,
  NOT_AUTHORIZED_TO_REQUEST_CREDENTIAL = 400036,
  NOT_AUTHORIZED_TO_MANAGE_REQUEST_CREDENTIAL = 400037,
  NOT_AUTHORIZED_TO_CANCEL_CREDENTIAL = 400038,
  NOT_AUTHORIZED_TO_READ_USER = 400039,
  CREDENTIAL_REQUEST_ALREADY_EXIST = 400040,
  PROFILE_DOES_NOT_HAVE_LINKED_WALLET = 400041,
  CREDENTIAL_INVALID_METADATA = 400042,
}

/**
 * Job kind options.
 */
export enum JobKind {
}

/**
 * Payments kinds.
 */
export enum PaymentKind {
  CREDIT_CARD = 1,
}

/**
 * Credential stages.
 */
export enum CredentialStage {
  REQUEST = 1,
  REJECTED = 2,
  CANCELED = 3,
  PENDING = 4,
  COMPLETED = 5,
  FAILED = 6,
  ISSUING = 7,
  ISSUING_FAILED = 8,
}
